<a href="https://colab.research.google.com/github/tanuja1308/Multiple_disease_prediction_model/blob/main/Dyslexia_SVM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
from google.colab import files
files.upload()

Saving labelled_data_new.csv to labelled_data_new.csv


{'labelled_data_new.csv': b'Language_vocab,Memory,Speed,Visual_discrimination,Audio_Discrimination,Survey_Score,Label\r\n0.5,0.6,0.5,0.8,0.6,0.7,1.0\r\n0.6,0.7,0.8,0.9,0.5,0.8,2.0\r\n0.6,0.4,0.3,0.3,0.4,0.6,1.0\r\n0.3,0.5,0.2,0.1,0.3,0.5,0.0\r\n0.7,0.6,0.7,0.8,0.9,0.5,2.0\r\n0.4,0.1,0.0,0.1,0.4,0.2,0.0\r\n0.8,1.0,0.8,0.9,0.6,0.6,2.0\r\n0.5,0.3,0.5,0.4,0.7,0.4,1.0\r\n0.6,0.5,0.5,0.4,0.6,0.5,1.0\r\n0.6,0.7,0.7,0.8,0.7,0.6,1.0\r\n0.7,0.7,0.5,0.7,0.8,0.8,1.0\r\n0.5,0.6,0.6,0.6,0.7,0.6,1.0\r\n0.9,0.6,0.5,0.9,0.7,0.7,2.0\r\n0.6,0.4,0.4,0.6,0.5,0.6,1.0\r\n0.7,0.6,0.4,0.3,0.4,0.3,1.0\r\n0.6,0.5,0.5,0.5,0.4,0.4,1.0\r\n0.0,0.2,0.3,0.0,0.3,0.2,0.0\r\n0.4,0.3,0.3,0.1,0.4,0.4,0.0\r\n0.7,0.7,0.8,0.7,0.7,0.9,2.0\r\n0.5,0.6,0.6,0.4,0.5,0.3,1.0\r\n0.5,0.6,0.3,0.4,0.3,0.6,1.0\r\n0.7,0.6,0.6,0.9,0.7,0.7,2.0\r\n1.0,0.8,0.9,0.5,0.7,0.8,2.0\r\n0.6,0.3,0.4,0.5,0.5,0.5,1.0\r\n0.6,0.6,0.7,0.5,0.6,0.8,1.0\r\n0.3,0.4,0.5,0.5,0.4,0.6,1.0\r\n0.3,0.5,0.5,0.4,0.4,0.4,1.0\r\n1.0,0.8,0.6,0.6,0.7,0.7,2.0\r\n0.7,0.5,0.6

In [4]:
data = pd.read_csv('labelled_data_new.csv')
data

Language_vocab  Memory  Speed  Visual_discrimination  \
0               0.5     0.6    0.5                    0.8   
1               0.6     0.7    0.8                    0.9   
2               0.6     0.4    0.3                    0.3   
3               0.3     0.5    0.2                    0.1   
4               0.7     0.6    0.7                    0.8   
..              ...     ...    ...                    ...   
495             0.4     0.3    0.1                    0.4   
496             0.4     0.6    0.5                    0.6   
497             0.7     0.5    0.8                    0.9   
498             0.3     0.5    0.4                    0.6   
499             0.7     0.7    0.8                    0.6   

     Audio_Discrimination  Survey_Score  Label  
0                     0.6           0.7    1.0  
1                     0.5           0.8    2.0  
2                     0.4           0.6    1.0  
3                     0.3           0.5    0.0  
4                     0.9           0.5    2.0  
..                    ...           ...    ...  
495                   0.2           0.5    0.0  
496                   0.5           0.4    1.0  
497                   0.8           0.5    1.0  
498                   0.6           0.6    1.0  
499                   0.8           0.6    2.0  

[500 rows x 7 columns]

In [16]:
data.drop(['Label'],axis=1)

Language_vocab  Memory  Speed  Visual_discrimination  \
0               0.5     0.6    0.5                    0.8   
1               0.6     0.7    0.8                    0.9   
2               0.6     0.4    0.3                    0.3   
3               0.3     0.5    0.2                    0.1   
4               0.7     0.6    0.7                    0.8   
..              ...     ...    ...                    ...   
495             0.4     0.3    0.1                    0.4   
496             0.4     0.6    0.5                    0.6   
497             0.7     0.5    0.8                    0.9   
498             0.3     0.5    0.4                    0.6   
499             0.7     0.7    0.8                    0.6   

     Audio_Discrimination  Survey_Score  
0                     0.6           0.7  
1                     0.5           0.8  
2                     0.4           0.6  
3                     0.3           0.5  
4                     0.9           0.5  
..                    ...           ...  
495                   0.2           0.5  
496                   0.5           0.4  
497                   0.8           0.5  
498                   0.6           0.6  
499                   0.8           0.6  

[500 rows x 6 columns]

In [18]:
X = data
y = data.Label

In [21]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.7,random_state=10)

In [22]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train, y_train)

SVC(random_state=0)

In [23]:
y_pred = classifier.predict(X_test)

In [24]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[ 39   2   0]
 [  6 171  15]
 [  0   2 115]]


0.9285714285714286